services:
  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto
    volumes:
    - "/srv/mosquitto/config:/mosquitto/config"
    - "/srv/mosquitto/log:/mosquitto/log"
    - "/srv/mosquitto/data/:/mosquitto/data"
    restart: always
    ports:
    - "1883:1883" 

  couchdb:
    container_name: plantcare-couchdb
    image: couchdb:3.4.4
    restart: always
    ports:
      - "5984:5984"
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=secret
    volumes:
      - /srv/couchdb/data:/opt/couchdb/data
    user: "1000:1000"

  nextjs:
    container_name: plantcare-webapp
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - COUCHDB_URL=http://admin:password@couchdb:5984
      - MQTT_BROKER_URL=mqtt://mosquitto:1883
    volumes:
      - ./app:/app
      - /app/node_modules
    depends_on:
      - couchdb
      - mosquitto
    command: npm run dev
    restart: always