services:
  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto
    volumes:
    - "/srv/mosquitto/config:/mosquitto/config"
    - "/srv/mosquitto/log:/mosquitto/log"
    - "/srv/mosquitto/data/:/mosquitto/data"
    restart: always
    ports:
    - "1883:1883" 

  mongo:
    container_name: plantcare-mongo
    image: bitnami/mongodb:latest
    restart: always
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=plantcare
      - MONGODB_ROOT_PASSWORD=password
    volumes:
      - /srv/mongodb/data:/bitnami/mongodb

  nextjs:
    container_name: plantcare-webapp
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb://plantcare-mongo:27017/plantcare
      - MQTT_BROKER_URL=mqtt://mosquitto:1883
    volumes:
      - ./app:/app
      - /app/node_modules
    depends_on:
      - mongo
      - mosquitto
    command: npm run dev
    restart: always